# Use snapshot mirrors

# Buster end of LTS ended at June 30, 2024.
# We set it up about one month later
SNAPSHOT_DATE="20240801T000000Z"

LB_MIRROR_BOOTSTRAP="http://snapshot.debian.org/archive/debian/${SNAPSHOT_DATE}/"
LB_MIRROR_CHROOT="$LB_MIRROR_BOOTSTRAP"
#LB_MIRROR_CHROOT_SECURITY="http://snapshot.debian.org/archive/debian-security/${SNAPSHOT_DATE}/"
LB_MIRROR_BINARY="$LB_MIRROR_BOOTSTRAP"
#LB_MIRROR_BINARY_SECURITY="$LB_MIRROR_CHROOT_SECURITY"
