# Snapshots have expired metadata. We disable validation

LB_APT_OPTIONS="\
--yes \
-o Acquire::Check-Valid-Until=false \
-o Acquire::AllowInsecureRepositories=true \
-o Acquire::AllowDowngradeToInsecureRepositories=true \
"
LB_APT_OPTIONS_BOOTSTRAP="$LB_APT_OPTIONS"
LB_APT_OPTIONS_CHROOT="$LB_APT_OPTIONS"
LB_APT_OPTIONS_BINARY="$LB_APT_OPTIONS"
