#!/bin/bash
# Rescapp Update-grub run script
# Copyright Adrian Gibanel Lopez
# Licensed under the GNU PUBLIC LICENSE 3.0

source ${RESCATUX_LIB_FILE}

set -x
set -v

# Select one of the partitions - BEGIN

n=0
LIST_VALUES=""
DESC_VALUES=""
for n_partition in ${TARGET_PARTITIONS}; do
  issue_value=`etc_issue ${n_partition}`
  issue_value=$(echo $issue_value | sed 's/\ /\-/')
  issue_value=$(echo $issue_value | sed 's/ /\-/')
  
  if [[ n -eq 0 ]] ; then
    LIST_VALUES="TRUE ${n_partition} ${issue_value}"
  else
    LIST_VALUES="${LIST_VALUES} FALSE ${n_partition} ${issue_value}"
  fi
let n=n+1
done

echo -e -n "a: $LIST_VALUES\n"

ans=$(zenity ${ZENITY_COMMON_OPTIONS}  --list  --text "Which partition do you want to Filesystem check with automatic fix?\n Please be patient. \nWhenever filesystem is finished a window will appear." --radiolist  --column "Select" --column "Partition" --column "Desc" ${LIST_VALUES}); echo $ans
# Lets suppose that selected partition is: sda3
SELECTED_PARTITION="$ans"
# Select one of the partitions - END


n_partition=${SELECTED_PARTITION}

if ( fsck /dev/stdout -fy /dev/${SELECTED_PARTITION} | tee >(zenity ${ZENITY_COMMON_OPTIONS} --text "Running forced filesystem check and fix" --progress --pulsate) >> /dev/stdout ) ; then
	zenity ${ZENITY_COMMON_OPTIONS} --info --title="Success!" --text="Filesystem check with automatic fix was OK! :)";
else 
	zenity ${ZENITY_COMMON_OPTIONS} --info --title="Failure!" --text="Filesystem check with automatic fix went wrong! :(";
fi
