#!/bin/bash
# Rescapp Update-grub run script
# Copyright Adrian Gibanel Lopez
# Licensed under the GNU PUBLIC LICENSE 3.0

source ${RESCATUX_LIB_FILE}

set -x
set -v

echo $TARGET_PARTITIONS

#SBIN_GRUB_PARTITIONS=""
RESCATUX_ROOT_MNT=/mnt/rescatux
LINUX_OS_DETECTOR="/etc/issue"
#GRUB_INSTALL_BINARY=/etc/issue
GRUB_INSTALL_BINARY=grub-install
UPDATE_GRUB_BINARY=update-grub

#for n_partition in ${TARGET_PARTITIONS}; do
#	TMP_MNT_PARTITION=${RESCATUX_ROOT_MNT}/${n_partition}
#	TMP_DEV_PARTITION=/dev/${n_partition}
#	mkdir --parents ${TMP_MNT_PARTITION}
#	if $(mount -t auto ${TMP_DEV_PARTITION} ${TMP_MNT_PARTITION} 2> /dev/null) ; then
#		#echo -e -n "Detectada particion: ${n_partition}\n";
#		if [[ -e ${TMP_MNT_PARTITION}${LINUX_OS_DETECTOR} ]] ; then
#		  #echo -e -n "Detectado grub-install en particion: ${n_partition}\n"
#		  SBIN_GRUB_PARTITIONS="${SBIN_GRUB_PARTITIONS} ${n_partition}"
#		fi
#		umount ${TMP_MNT_PARTITION};
#	fi
#done

#echo -e -n "Detected grub-install partitions: ${SBIN_GRUB_PARTITIONS}\n"





# MAIN PROGRAM

# TODO: FETCH WIDTH AND HEIGHT FROM COMMAND LINE OR SO

GRUB_INSTALL_MBR_WIDTH="600"
GRUB_INSTALL_MBR_HEIGHT="400"
ZENITY_COMMON_OPTIONS="--width=${GRUB_INSTALL_MBR_WIDTH} --height=${GRUB_INSTALL_MBR_HEIGHT}"

TMP_FOLDER="/tmp"
DEVICE_MAP_NUMBERED_FILE="${TMP_FOLDER}/device.map.numbered"
DEVICE_MAP_RESCATUX_STR="device.map.rescatux"
DEVICE_MAP_BACKUP_STR="device.map.rescatux.backup"

#alias zenity = 'zenity ${ZENITY_COMMON_OPTIONS}' # It does not seem to work
# Select one of the partitions - BEGIN

n=0
LIST_VALUES=""
DESC_VALUES=""
for n_partition in ${TARGET_PARTITIONS}; do
  issue_value=`etc_issue ${n_partition}`
  issue_value=$(echo $issue_value | sed 's/\ /\-/')
  issue_value=$(echo $issue_value | sed 's/ /\-/')
  
  if [[ n -eq 0 ]] ; then
    LIST_VALUES="TRUE ${n_partition} ${issue_value}"
  else
    LIST_VALUES="${LIST_VALUES} FALSE ${n_partition} ${issue_value}"
  fi
let n=n+1
done

echo -e -n "a: $LIST_VALUES\n"

ans=$(zenity ${ZENITY_COMMON_OPTIONS}  --list  --text "Which partition do you want to Filesystem check with automatic fix?\n Please be patient. \nWhenever filesystem is finished a window will appear." --radiolist  --column "Select" --column "Partition" --column "Desc" ${LIST_VALUES}); echo $ans
# Lets suppose that selected partition is: sda3
SELECTED_PARTITION="$ans"
# Select one of the partitions - END


n_partition=${SELECTED_PARTITION}

if ( fsck /dev/stdout -fy /dev/${SELECTED_PARTITION} | tee >(zenity ${ZENITY_COMMON_OPTIONS} --text "Running forced filesystem check and fix" --progress --pulsate) >> /dev/stdout ) ; then
	zenity ${ZENITY_COMMON_OPTIONS} --info --title="Success!" --text="Filesystem check with automatic fix was OK! :)";
else 
	zenity ${ZENITY_COMMON_OPTIONS} --info --title="Failure!" --text="Filesystem check with automatic fix went wrong! :(";
fi
