#!/bin/bash
# Rescapp Share Log run script
# Copyright (C) 2012,2013,2014,2015,2016 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.
source ${RESCATUX_LIB_FILE}

# 1 parametre = Selected file
function rtux_share_log () {
local SELECTED_FILE="$1"

pastebinit -i "${RESCATUX_PATH}${LOG_DIRECTORY}\
/${SELECTED_FILE}" -b ${RESCATUX_PASTEBIN_URL} \
-a resc_$$ -f bash

}

LOG_CHOOSE_STR="Please choose a log file"
LOG_STR="log"
PASTEBIN_HINT="Right-click and select copy please. You will be able to paste it later at the chat option"

m=1
for ffile in ${RESCATUX_PATH}${LOG_DIRECTORY}/* ; do

  BFILE=$(basename $ffile)
  if [[ m -eq 1 ]] ; then
    LOG_LIST_VALUES="TRUE ${BFILE}"
  else
    LOG_LIST_VALUES="${LOG_LIST_VALUES} FALSE ${BFILE}"
  fi
  let m=m+1
done

SELECTED_FILE=$(zenity ${ZENITY_COMMON_OPTIONS} \
	  --list  \
	  --text "${LOG_CHOOSE_STR}" \
	  --radiolist  \
	  --column "${SELECT_STR}" \
	  --column "${LOG_STR}" \
	  ${LOG_LIST_VALUES});

PASTEBIN_URL=$(rtux_share_log "${SELECTED_FILE}")

zenity ${ZENITY_COMMON_OPTIONS} \
	--entry \
	--text "${PASTEBIN_HINT}" \
	--entry-text="${PASTEBIN_URL}"

