#!/bin/bash
# Rescapp make_common script
# Copyright (C) 2012 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.


# This script assumes apt-get install live-helper has been done
# This script assumes that the user has sudo permissions on lh build


set -x
set -v

# Fetch version from folder directory name
VERSION=`head -1 VERSION`

RESCATUX_FILES="rescapp.py order.py setbackground.sh chat web grub-install update-grub grub.lis grub rescatux.lis show_log support support.lis fsck fs fs.lis images logos about.lis about about-rescapp rescatux_lib.sh share_log win win.lis winmbr winpass bootinfoscript share_log_forum VERSION COPYING rescapp_launcher.sh help-rescapp pass.lis pass chpasswd sudoers"
RESCATUX_EMPTY_DIRS="log"

DESKTOP_METAPACKAGE="razorqt lightdm task-desktop"
CORE_PACKAGES="live-tools user-setup sudo eject"

# This was for lenny
#MIRROR_BOOTSTRAP="http://192.168.0.50/debian/"
#MIRROR_CHROOT="http://192.168.0.50/debian"

#This is for squeeze
MIRROR_BOOTSTRAP="http://127.0.0.1:9999/debian"
MIRROR_CHROOT="http://127.0.0.1:9999/debian"
SID_MIRROR="http://127.0.0.1:9999/debian/"
SIDUCTION_EXTRA_MIRROR="http://ftp.spline.de/mirrors/siduction/extra"

ARCH="i386"
DISTRIBUTION="testing" # Todo: Select with a switch
DISTRIBUTION_OPTION="-d ${DISTRIBUTION}"

ARCH_OPTION="-a ${ARCH}" # Todo: Select with a switch
RESCATUX_STR="rescatux"

RESCATUX_MEDIA_STR="${RESCATUX_STR}_${MEDIA_STR}"
BASE_FILENAME="${RESCATUX_MEDIA_STR}_${ARCH}_`echo ${LINUX_FLAVOURS} | sed s/' '/'-'/g`_`head -n 1 VERSION`"
CURRENT_FOLDER=$PWD

TEMP_FOLDER="$(pwd)/live-build"
SKEL_FOLDER="config/includes.chroot/etc/skel"

CHROOT_SOURCES_FOLDER="config/archives"
SID_CHROOT_CONFIG="config/archives/sid.list.chroot"
SIDUCTION_EXTRA_CHROOT_CONFIG="config/archives/siduction.extra.list.chroot"
CHROOT_APT_CONFIG_FOLDER1="config/apt/"
APT_PREFERENCES1="config/apt/preferences"
CHROOT_APT_CONFIG_FOLDER2="config/archives/"
APT_PREFERENCES2="config/archives/sid.pref"
CHROOT_APT_CONFIG_FOLDER3="config/archives/"
APT_PREFERENCES3="config/archives/sid.pref.chroot"
PACKAGES_CHROOT_FOLDER="config/packages.chroot"


CUSTOM_PACKAGES_LISTS_FOLDER="config/package-lists"

#LIVE_HELPER_LISTS_FOLDER="/usr/share/live-helper/lists"
LIVE_HELPER_LISTS_FOLDER="/usr/share/live/build/lists"
RLE_FOLDER="config/binary_syslinux"
RLE_FILE="${RLE_FOLDER}/${RESCATUX_STR}.rle"

CHNTPWNG_BINARY="../TRINITY/chntpwsource/chntpw-NG/chntpw"

mkdir --parents $TEMP_FOLDER/${RLE_FOLDER}
# Generate logo - Begin
cd logo
./generate_logo.sh "${RESCATUX_STR}" "${VERSION}" "${TEMP_FOLDER}/${RLE_FILE}"
cd ..
# Generate logo - End

mkdir --parents $TEMP_FOLDER/
# Special backported passwd packages
mkdir --parents ${TEMP_FOLDER}/${PACKAGES_CHROOT_FOLDER}
# Backported passwd no longer needed in wheezy
#cp ${BACKPORTED_PASSWD} ${TEMP_FOLDER}/${PACKAGES_CHROOT_FOLDER}

mkdir --parents $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/
mkdir --parents $TEMP_FOLDER/${SKEL_FOLDER}/.config/autostart/
mkdir --parents $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}
mkdir --parents $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/rescapp
cp -r ${RESCATUX_FILES} $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/rescapp/
for n_empty_dir in ${RESCATUX_EMPTY_DIRS} ; do
  mkdir $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/rescapp/${n_empty_dir}
done
cp ${CHNTPWNG_BINARY} $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/rescapp/
cp rescapp.sh.desktop $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/
cp rescapp.sh.desktop $TEMP_FOLDER/${SKEL_FOLDER}/.config/autostart/
cp setbackground.sh.desktop $TEMP_FOLDER/${SKEL_FOLDER}/.config/autostart/
cd $TEMP_FOLDER
#sudo cp ${LIVE_HELPER_LISTS_FOLDER}/gnome-core ${LIVE_HELPER_LISTS_FOLDER}/${RESCATUX_MEDIA_STR}
sudo bash -c "echo \"${CORE_PACKAGES}\" > $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}/recommends.list.chroot"
sudo bash -c "echo \"${DESKTOP_METAPACKAGE}\" > $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}/rescatux_desktop.list.chroot"
sudo bash -c "echo \"${PACKAGES}\" > $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}/${RESCATUX_MEDIA_STR}.list.chroot"

mkdir --parents $TEMP_FOLDER/${CHROOT_SOURCES_FOLDER}
echo -e -n "deb ${SID_MIRROR} sid main" > $TEMP_FOLDER/${SID_CHROOT_CONFIG}
echo -e -n "deb ${SIDUCTION_EXTRA_MIRROR} unstable main" > $TEMP_FOLDER/${SIDUCTION_EXTRA_CHROOT_CONFIG}

mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER1}
mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER2}
mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER3}

tee $TEMP_FOLDER/${APT_PREFERENCES1} \
$TEMP_FOLDER/${APT_PREFERENCES2} \
$TEMP_FOLDER/${APT_PREFERENCES3} <<END
Package: razorqt
Pin: release n=sid
Pin-Priority: 600

Package: *
Pin: release n=sid
Pin-Priority: 1

Package: qtfm
Pin: release a=unstable
Pin-Priority: 600

Package: *
Pin: release a=unstable
Pin-Priority: 1

END

# Initial lb config
if [ ! -d .build ] ; then
  lb config
  # Copy auto examples
  cp /usr/share/doc/live-build/examples/auto/* auto/
fi

# Generate auto/config
cat << EOF > auto/config
#!/bin/sh

lb config noauto \\
  --updates false \\
  --apt-recommends false \\
  --linux-flavours "${LINUX_FLAVOURS}" \\
  ${DISTRIBUTION_OPTION} \\
  ${ARCH_OPTION} \\
  ${BOOT_OPTION} \\
  --mirror-bootstrap "${MIRROR_BOOTSTRAP}" \\
  --mirror-chroot "${MIRROR_CHROOT}" \\
  --apt-options "--force-yes --yes -o Acquire::Check-Valid-Until=false" \\
        "\${@}"
EOF

sudo bash -c "lb config"
sudo bash -c "lb clean"

sudo bash -c "lb build 2>&1 | tee ${CURRENT_FOLDER}/${BASE_FILENAME}_build.log"
mv binary${IS_HYBRID}.${FILE_EXTENSION} ${CURRENT_FOLDER}/${BASE_FILENAME}.${FILE_EXTENSION}
mv binary.packages ${CURRENT_FOLDER}/${BASE_FILENAME}.packages
cd ${CURRENT_FOLDER}
md5sum ${BASE_FILENAME}.${FILE_EXTENSION} > ${BASE_FILENAME}.${FILE_EXTENSION}.md5
echo "${BASE_FILENAME}.${FILE_EXTENSION} (and md5sum) DONE!"
