#!/bin/bash
# Rescapp make_common script
# Copyright (C) 2012 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.


# This script assumes apt-get install live-helper has been done
# This script assumes that the user has sudo permissions on lh build


set -x
set -v

# Fetch version from folder directory name
VERSION=`head -1 VERSION`

RESCATUX_FILES=" \
 logos \
 "
RESCATUX_EMPTY_DIRS="log"

DESKTOP_METAPACKAGE="task-lxde-desktop"
CORE_PACKAGES="live-tools user-setup sudo eject"

RESCATUX_RELEASE_DIR="$(pwd)/rescatux-release"

# This was for lenny
#MIRROR_BOOTSTRAP="http://192.168.0.50/debian/"
#MIRROR_CHROOT="http://192.168.0.50/debian"

#This is for squeeze
MIRROR_BOOTSTRAP="http://127.0.0.1:9999/debian"
MIRROR_CHROOT="http://127.0.0.1:9999/debian"
SID_MIRROR="http://snapshot.debian.org/archive/debian/20151017T100905Z/"
JESSIE_MIRROR="http://127.0.0.1:9999/debian/"
BOOTREPAIR_MIRROR="http://ppa.launchpad.net/yannubuntu/boot-repair/ubuntu"
RESCATUX_TAILS_GREETER="/home/adrian/gnu/rescatux/tails_greeter_git/tails-greeter_0.8.5_all.deb"

ARCH="i386"
DISTRIBUTION="jessie" # Todo: Select with a switch
DISTRIBUTION_OPTION="-d ${DISTRIBUTION}"

ARCH_OPTION="-a ${ARCH}" # Todo: Select with a switch
RESCATUX_STR="rescatux"

RESCATUX_MEDIA_STR="${RESCATUX_STR}_${MEDIA_STR}"
BASE_FILENAME=${BASE_FILENAME-"${RESCATUX_MEDIA_STR}_${ARCH}_`echo ${LINUX_FLAVOURS} | sed s/' '/'-'/g`_`head -n 1 VERSION`"}
CURRENT_FOLDER=$PWD

TEMP_FOLDER="$(pwd)/live-build"
SKEL_FOLDER="config/includes.chroot/etc/skel"

CHROOT_SOURCES_FOLDER="config/archives"
SID_CHROOT_CONFIG="config/archives/sid.list.chroot"
JESSIE_CHROOT_CONFIG="config/archives/jessie.list.chroot"
BOOTREPAIR_CHROOT_CONFIG="config/archives/bootrepair.list.chroot"
CHROOT_APT_CONFIG_FOLDER1="config/apt/"
APT_PREFERENCES1="config/apt/preferences"
CHROOT_APT_CONFIG_FOLDER2="config/archives/"
APT_PREFERENCES2="config/archives/sid.pref"
CHROOT_APT_CONFIG_FOLDER3="config/archives/"
APT_PREFERENCES3="config/archives/sid.pref.chroot"
PACKAGES_CHROOT_FOLDER="config/packages.chroot"


CUSTOM_PACKAGES_LISTS_FOLDER="config/package-lists"

#LIVE_HELPER_LISTS_FOLDER="/usr/share/live-helper/lists"
LIVE_HELPER_LISTS_FOLDER="/usr/share/live/build/lists"
RESCATUX_DATA_FOLDER="config/includes.chroot/usr/share/rescatux-data/"
RESCATUX_BIN_FOLDER="config/includes.chroot/usr/bin/"
RLE_FOLDER="config/binary_syslinux"
RLE_FILE="${RLE_FOLDER}/${RESCATUX_STR}.rle"

CHNTPW_PATH="../subproyectos/chntpwsource/chntpw-NG"
SAMPASSWD_BINARY="${CHNTPW_PATH}/sampasswd"
SAMUNLOCK_BINARY="${CHNTPW_PATH}/samunlock"

LB_ISO_APPLICATION="Rescatux Gnu/Linux ${VERSION}"
LB_ISO_PUBLISHER="Rescatux team"
LB_ISO_VOLUME="Rescatux${VERSION}"

mkdir --parents $TEMP_FOLDER/${RLE_FOLDER}
# Generate logo - Begin
cd logo
sudo bash -c "./generate_logo.sh \"${RESCATUX_STR}\" \"${VERSION}\" \"${TEMP_FOLDER}/${RLE_FILE}\""
cd ..
# Generate logo - End

mkdir --parents $TEMP_FOLDER/


sudo rm -rf ${TEMP_FOLDER}/config
cp -a live-config ${TEMP_FOLDER}/config
# Special backported passwd packages
mkdir --parents ${TEMP_FOLDER}/${PACKAGES_CHROOT_FOLDER}
# Backported passwd no longer needed in jessie
#cp ${BACKPORTED_PASSWD} ${TEMP_FOLDER}/${PACKAGES_CHROOT_FOLDER}
cp ${RESCATUX_TAILS_GREETER} ${TEMP_FOLDER}/${PACKAGES_CHROOT_FOLDER}
mkdir --parents $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}
mkdir --parents $TEMP_FOLDER/${RESCATUX_DATA_FOLDER}
mkdir --parents $TEMP_FOLDER/${RESCATUX_BIN_FOLDER}
mkdir --parents $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/
cp -r rescapp $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/
for n_empty_dir in ${RESCATUX_EMPTY_DIRS} ; do
  mkdir --parents $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/rescapp/${n_empty_dir}
done
cp ${SAMUNLOCK_BINARY} ${SAMPASSWD_BINARY} $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/rescapp/
cp rescapp/rescapp.sh.desktop $TEMP_FOLDER/${SKEL_FOLDER}/Desktop/
cp rescapp/rescapp.sh.desktop $TEMP_FOLDER/${SKEL_FOLDER}/.config/autostart/
cp -r logos $TEMP_FOLDER/${RESCATUX_DATA_FOLDER}
cp set-rescatux-background.sh $TEMP_FOLDER/${RESCATUX_BIN_FOLDER}
for n_splash_dir in extlinux isolinux pxelinux syslinux ; do
  sed -i "s/@RESCATUX_VERSION@/${VERSION}/g" \
    ${TEMP_FOLDER}/config/bootloaders/${n_splash_dir}/splash.svg
done
cd $TEMP_FOLDER
#sudo cp ${LIVE_HELPER_LISTS_FOLDER}/gnome-core ${LIVE_HELPER_LISTS_FOLDER}/${RESCATUX_MEDIA_STR}
sudo bash -c "echo \"${CORE_PACKAGES}\" > $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}/recommends.list.chroot"
sudo bash -c "echo \"${DESKTOP_METAPACKAGE}\" > $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}/rescatux_desktop.list.chroot"
sudo bash -c "echo \"${PACKAGES}\" > $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}/${RESCATUX_MEDIA_STR}.list.chroot"
sudo bash -c "echo \"${SELINUX_PACKAGES}\" > $TEMP_FOLDER/${CUSTOM_PACKAGES_LISTS_FOLDER}/selinux.list.binary"

mkdir --parents $TEMP_FOLDER/${CHROOT_SOURCES_FOLDER}
echo -e -n "deb ${SID_MIRROR} sid main" > $TEMP_FOLDER/${SID_CHROOT_CONFIG}
echo -e -n "deb ${JESSIE_MIRROR} jessie main" > $TEMP_FOLDER/${JESSIE_CHROOT_CONFIG}
echo -e -n "deb ${BOOTREPAIR_MIRROR} trusty main" > $TEMP_FOLDER/${BOOTREPAIR_CHROOT_CONFIG}

mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER1}
mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER2}
mkdir --parents $TEMP_FOLDER/${CHROOT_APT_CONFIG_FOLDER3}

tee $TEMP_FOLDER/${APT_PREFERENCES1} \
$TEMP_FOLDER/${APT_PREFERENCES2} \
$TEMP_FOLDER/${APT_PREFERENCES3} <<END
Package: *
Pin: release n=sid
Pin-Priority: 1
END

# Initial lb config
if [ ! -d .build ] ; then
  lb config
  # Copy auto examples
  cp /usr/share/doc/live-build/examples/auto/* auto/
fi

# Generate auto/config
cat << EOF > auto/config
#!/bin/sh

lb config noauto \\
  --bootloaders "${BOOTLOADERS_OPTION}" \\
  --updates false \\
  --apt-recommends false \\
  --linux-flavours "${LINUX_FLAVOURS}" \\
  ${DISTRIBUTION_OPTION} \\
  ${ARCH_OPTION} \\
  ${BOOT_OPTION} \\
  --mirror-bootstrap "${MIRROR_BOOTSTRAP}" \\
  --mirror-chroot "${MIRROR_CHROOT}" \\
  --apt-options "--force-yes --yes -o Acquire::Check-Valid-Until=false" \\
  --iso-application "${LB_ISO_APPLICATION}" \\
  --iso-publisher "${LB_ISO_PUBLISHER}" \\
  --iso-volume "${LB_ISO_VOLUME}" \\
  --bootappend-live "boot=live config quiet splash selinux=1 security=selinux enforcing=0 locales=en_US.UTF-8" \\
        "\${@}"
EOF

sudo bash -c "lb config"
sudo bash -c "lb clean"

sudo bash -c "lb build 2>&1 | tee ${RESCATUX_RELEASE_DIR}/${BASE_FILENAME}_build.log"
mv live-image-i386${IS_HYBRID}.${FILE_EXTENSION} ${RESCATUX_RELEASE_DIR}/${BASE_FILENAME}.${FILE_EXTENSION}
mv live-image-i386.packages ${RESCATUX_RELEASE_DIR}/${BASE_FILENAME}.packages
cd ${RESCATUX_RELEASE_DIR}
md5sum ${BASE_FILENAME}.${FILE_EXTENSION} > ${BASE_FILENAME}.${FILE_EXTENSION}.md5
echo "${BASE_FILENAME}.${FILE_EXTENSION} (and md5sum) DONE!"
cd ${CURRENT_FOLDER}