#!/bin/bash
# rescatux_common_packages
# Copyright (C) 2014,2015,2016 Adrian Gibanel Lopez
#
# Rescatux is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

# This script assumes apt-get install live-helper has been done
# This script assumes that the user has sudo permissions on lh build

LXDE_PACKAGES="network-manager-gnome feh"
PYTHON_PACKAGES="python-sip python-qt4"
RAID_PACKAGES="dmraid"
LVM_PACKAGES="lvm2"
SYNAPTIC_PACKAGES="synaptic"
GKSU_PACKAGES="gksu"
GPARTED_PACKAGES="gparted gpart"
BOOTREPAIR_PACKAGES="boot-repair \
 boot-sav \
 gawk \
 pastebinit \
 xz-utils \
 gettext-base \
 glade2script \
 os-prober \
 parted \
 xdg-utils \
 zenity \
 boot-sav-extra \
 gksu \
 lsb-release \
 zip \
 dmraid \
 lvm2 \
 mbr \
 mdadm \
 os-uninstaller \
 clean-ubiquity \
 python \
 gir1.2-gtk-3.0 \
 python-gi \
 ntfs-3g \
 efibootmgr \
 syslinux-common \
 cryptsetup \
 boot-info \
 "
TESTDISK_PACKAGES="testdisk \
 e2fslibs \
 libc6 \
 libcomerr2 \
 libjpeg62-turbo \
 libncursesw5 \
 libntfs-3g852 \
 libtinfo5 \
 libuuid1 \
 zlib1g \
 ntfs-3g \
 "
CRYPTSETUP_PACKAGES="cryptsetup \
 libcryptsetup4 \
 cryptsetup-bin \
 "
FILESYSTEM_PACKAGES="reiserfsprogs \
 reiser4progs \
 btrfs-tools \
 xfsprogs \
 xfsdump \
 "

TAILSGREETER_PACKAGES="\
 accountsservice \
 console-setup \
 console-setup-linux \
 dconf-cli \
 evolution-data-server \
 evolution-data-server-common \
 gcr \
 gdm3 \
 gir1.2-accountsservice-1.0 \
 gir1.2-atspi-2.0 \
 gir1.2-caribou-1.0 \
 gir1.2-clutter-1.0 \
 gir1.2-cogl-1.0 \
 gir1.2-coglpango-1.0 \
 gir1.2-gck-1 \
 gir1.2-gcr-3 \
 gir1.2-gdesktopenums-3.0 \
 gir1.2-gdm3 \
 gir1.2-gkbd-3.0 \
 gir1.2-gnomebluetooth-1.0 \
 gir1.2-gnomedesktop-3.0 \
 gir1.2-ibus-1.0 \
 gir1.2-javascriptcoregtk-3.0 \
 gir1.2-json-1.0 \
 gir1.2-mutter-3.0 \
 gir1.2-networkmanager-1.0 \
 gir1.2-nmgtk-1.0 \
 gir1.2-polkit-1.0 \
 gir1.2-soup-2.4 \
 gir1.2-telepathyglib-0.12 \
 gir1.2-telepathylogger-0.2 \
 gir1.2-upowerglib-1.0 \
 gir1.2-webkit-3.0 \
 gir1.2-xkl-1.0 \
 gjs \
 gnome-backgrounds \
 gnome-desktop3-data \
 gnome-flashback \
 gnome-flashback-common \
 gnome-icon-theme-symbolic \
 gnome-keyring \
 gnome-session-bin \
 gnome-settings-daemon \
 gnome-shell \
 gnome-shell-common \
 gnome-themes-standard \
 gnome-themes-standard-data \
 kbd \
 libaccountsservice0 \
 libasyncns0 \
 libboost-date-time1.55.0 \
 libboost-system1.55.0 \
 libboost-thread1.55.0 \
 libcamel-1.2-49 \
 libcanberra-gtk3-0 \
 libcanberra0 \
 libcaribou-common \
 libcaribou0 \
 libclutter-1.0-0 \
 libcogl-pango20 \
 libcogl-path20 \
 libcogl20 \
 libcurl3-gnutls \
 libebackend-1.2-7 \
 libebook-1.2-14 \
 libebook-contacts-1.2-0 \
 libecal-1.2-16 \
 libedata-book-1.2-20 \
 libedata-cal-1.2-23 \
 libedataserver-1.2-18 \
 libelfg0 \
 libflac8 \
 libgck-1-0 \
 libgcr-3-common \
 libgcr-base-3-1 \
 libgcr-ui-3-1 \
 libgdata-common \
 libgdata19 \
 libgdm1 \
 libgee-0.8-2 \
 libgeocode-glib0 \
 libgjs0e \
 libglib2.0-bin \
 libglib2.0-data \
 libgnome-bluetooth13 \
 libgnome-desktop-3-10 \
 libgnomekbd-common \
 libgnomekbd8 \
 libgoa-1.0-0b \
 libgoa-1.0-common \
 libgweather-3-6 \
 libgweather-common \
 libibus-1.0-5 \
 libical1a \
 libimobiledevice4 \
 libinput5 \
 libltdl7 \
 libmission-control-plugins0 \
 libmozjs-24-0 \
 libmutter0e \
 libnspr4 \
 libnss3 \
 liboauth0 \
 libogg0 \
 libpackagekit-glib2-18 \
 libphonenumber6 \
 libplist2 \
 libprotobuf9 \
 libpulse-mainloop-glib0 \
 libpulse0 \
 libsndfile1 \
 libtdb1 \
 libtelepathy-glib0 \
 libtelepathy-logger3 \
 libupower-glib3 \
 libusb-1.0-0 \
 libusbmuxd2 \
 libvorbis0a \
 libvorbisenc2 \
 libvorbisfile3 \
 libwacom-common \
 libwacom2 \
 libwayland-egl1-mesa \
 libxcb-randr0 \
 libxcb-xkb1 \
 libxkbcommon-x11-0 \
 mutter \
 mutter-common \
 nautilus-data \
 p11-kit \
 p11-kit-modules \
 python-dbus \
 python-dbus-dev \
 python-gobject \
 python-gobject-2 \
 python-lxml \
 python-pycountry \
 python-pyicu \
 telepathy-mission-control-5 \
 ttf-unifont \
 upower \
 xwayland \
 metacity \
 libmetacity-private2 \
 metacity-common \
 sgml-base \
"
SELINUX_PACKAGES="\
 libapol4 \
 libqpol1 \
 policycoreutils \
 python-ipy \
 python-selinux \
 python-semanage \
 python-sepolgen \
 python-sepolicy \
 python-setools \
 selinux-utils \
 selinux-basics \
 auditd \
 selinux-policy-default \
 setools \
"

GPT_PACKAGES="\
 gdisk \
"

PYTHON_PARTED_PACKAGES="python-parted"

COMMON_PACKAGES="${LXDE_PACKAGES} \
 ${PYTHON_PACKAGES} \
 ${RAID_PACKAGES} \
 ${LVM_PACKAGES} \
 ${SYNAPTIC_PACKAGES} \
 ${GKSU_PACKAGES} \
 ${GPARTED_PACKAGES} \
 ${BOOTREPAIR_PACKAGES} \
 ${TESTDISK_PACKAGES} \
 ${CRYPTSETUP_PACKAGES} \
 ${FILESYSTEM_PACKAGES} \
 ${SELINUX_PACKAGES} \
 ${GPT_PACKAGES} \
 ${TAILSGREETER_PACKAGES} \
 ${PYTHON_PARTED_PACKAGES} \
 zenity \
 iceweasel \
 xchat \
 syslinux \
 pastebinit \
 lilo \
 ntfs-3g \
 chntpw \
 samdump2 \
 bkhive \
 gawk\
 extundelete\
 locales \
 " # I add syslinux so that isohybrid command is recognised.
