#!/bin/bash
# rescatux_common_packages
# Copyright (C) 2014,2015,2016 Adrian Gibanel Lopez
#
# Rescatux is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

# This script assumes apt-get install live-helper has been done
# This script assumes that the user has sudo permissions on lh build

RESCAPP_PACKAGES="rescapp"
DESKTOP_METAPACKAGE="lxqt task-desktop"
LXQT_PACKAGES="\
 cmst \
 qterminal \
 faenza-icon-theme
"
SYNAPTIC_PACKAGES="synaptic"

GDDRESCUE_PACKAGES="gddrescue"
MYRESCUE_PACKAGES="myrescue"

COMMON_PACKAGES="${LXQT_PACKAGES} \
 ${SYNAPTIC_PACKAGES} \
 ${GDDRESCUE_PACKAGES} \
 ${MYRESCUE_PACKAGES} \
 ${RESCAPP_PACKAGES} \
 ${DESKTOP_METAPACKAGE} \
 firefox-esr \
 syslinux \
 gawk\
 extundelete\
 locales \
 ca-certificates \
 " # I add syslinux so that isohybrid command is recognised.
