#!/bin/bash
# rescatux_common_packages
# Copyright (C) 2014 Adrian Gibanel Lopez
#
# Rescatux is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

# This script assumes apt-get install live-helper has been done
# This script assumes that the user has sudo permissions on lh build

LXDE_PACKAGES="network-manager-gnome feh"
PYTHON_PACKAGES="python-sip python-qt4"
RAID_PACKAGES="dmraid"
LVM_PACKAGES="lvm2"
SYNAPTIC_PACKAGES="synaptic"
GKSU_PACKAGES="gksu"
GPARTED_PACKAGES="gparted gpart"
BOOTREPAIR_PACKAGES="boot-repair \
 boot-sav \
 gawk \
 pastebinit \
 xz-utils \
 gettext-base \
 glade2script \
 os-prober \
 parted \
 xdg-utils \
 zenity \
 boot-sav-extra \
 gksu \
 lsb-release \
 zip \
 dmraid \
 lvm2 \
 mbr \
 mdadm \
 os-uninstaller \
 clean-ubiquity \
 python \
 gir1.2-gtk-3.0 \
 python-gi \
 ntfs-3g \
 efibootmgr \
 syslinux-common \
 cryptsetup \
 boot-info \
 "
TESTDISK_PACKAGES="testdisk \
 e2fslibs \
 libc6 \
 libcomerr2 \
 libjpeg62-turbo \
 libncursesw5 \
 libntfs-3g852 \
 libtinfo5 \
 libuuid1 \
 zlib1g \
 ntfs-3g \
 "
CRYPTSETUP_PACKAGES="cryptsetup \
 libcryptsetup4 \
 cryptsetup-bin \
 "
FILESYSTEM_PACKAGES="reiserfsprogs \
 reiser4progs \
 btrfs-tools \
 xfsprogs \
 xfsdump \
 "

TAILSGREETER_PACKAGES="\
 accountsservice \
 console-setup \
 console-setup-linux \
 dconf-tools \
 gdm3 \
 gir1.2-accountsservice-1.0 \
 gir1.2-javascriptcoregtk-3.0 \
 gir1.2-soup-2.4 \
 gir1.2-webkit-3.0 \
 gir1.2-xkl-1.0 \
 gnome-desktop3-data \
 gnome-session-bin \
 gnome-settings-daemon \
 kbd \
 libaccountsservice0 \
 libarchive12 \
 libasyncns0 \
 libcanberra-gtk0 \
 libcanberra-gtk3-0 \
 libcanberra0 \
 libelf1 \
 libflac8 \
 libglib2.0-bin \
 libglib2.0-data \
 libgnome-desktop-3-2 \
 libgnomekbd-common \
 libgnomekbd7 \
 libimobiledevice2 \
 libjson-glib-1.0-0 \
 libjson0 \
 libltdl7 \
 libmetacity-private0a \
 libnettle4 \
 libnspr4 \
 libnss3 \
 libogg0 \
 libpackagekit-glib2-14 \
 libplist1 \
 libpulse-mainloop-glib0 \
 libpulse0 \
 libsndfile1 \
 libsoup-gnome2.4-1 \
 libtdb1 \
 libupower-glib1 \
 libusb-1.0-0 \
 libusbmuxd1 \
 libvorbis0a \
 libvorbisenc2 \
 libvorbisfile3 \
 libwacom-common \
 libwacom2 \
 metacity \
 metacity-common \
 module-init-tools \
 nautilus-data \
 pm-utils \
 powermgmt-base \
 python-dbus \
 python-dbus-dev \
 python-gobject \
 python-gobject-2 \
 python-lxml \
 python-pycountry \
 python-pyicu \
 sgml-base \
 ttf-unifont \
 upower \
 usbmuxd \
"

COMMON_PACKAGES="${LXDE_PACKAGES} \
 ${PYTHON_PACKAGES} \
 ${RAID_PACKAGES} \
 ${LVM_PACKAGES} \
 ${SYNAPTIC_PACKAGES} \
 ${GKSU_PACKAGES} \
 ${GPARTED_PACKAGES} \
 ${BOOTREPAIR_PACKAGES} \
 ${TESTDISK_PACKAGES} \
 ${CRYPTSETUP_PACKAGES} \
 ${FILESYSTEM_PACKAGES} \
 ${TAILSGREETER_PACKAGES} \
 zenity \
 iceweasel \
 xchat \
 syslinux \
 pastebinit \
 lilo \
 ntfs-3g \
 chntpw \
 samdump2 \
 bkhive \
 gawk\
 extundelete\
 locales \
 " # I add syslinux so that isohybrid command is recognised.
