#!/bin/bash
# TODO: Get this variables from a common config
FILEMANAGER_COMMAND="nautilus"
RESCATUX_ROOT="/home/user/Desktop"
LOG_DIRECTORY="log"
RESCATUX_LOG="${RESCATUX_ROOT}/${LOG_DIRECTORY}"


${FILEMANAGER_COMMAND} file://${RESCATUX_LOG} &



