#!/bin/bash
# Rescapp Chpasswd run script
# Copyright (C) 2012,2013,2014,2015,2016 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCATUX_LIB_FILE}

set -x
set -v

# Change selected user's password from the choosen Linux partition
# 1 parametre = Selected partition
# 2 parametre = Selected user
# 3 parametre = Choosen password
function rtux_Chpasswd () {

  local EXIT_VALUE=1 # Error by default
  local SELECTED_PARTITION="$1"
  local SELECTED_USER="$2"
  local CHOOSEN_PASS="$3"

  local n_partition=${SELECTED_PARTITION}

  local TMP_MNT_PARTITION=${RESCATUX_ROOT_MNT}/${n_partition}
  local TMP_DEV_PARTITION=/dev/${n_partition}
  mkdir --parents ${TMP_MNT_PARTITION}
  if $(mount -t auto ${TMP_DEV_PARTITION} ${TMP_MNT_PARTITION} 2> /dev/null)
    then
    mount -o bind /dev ${TMP_MNT_PARTITION}/dev
    mount -o bind /proc ${TMP_MNT_PARTITION}/proc
    mount -o bind /sys ${TMP_MNT_PARTITION}/sys

    if [[ -e ${TMP_MNT_PARTITION}${LINUX_OS_DETECTOR} ]] ; then

      echo "${SELECTED_USER}:${CHOOSEN_PASS}" | chpasswd -m --root ${TMP_MNT_PARTITION}
      EXIT_VALUE=$?
		  
    fi # Linux detector was found
    umount ${TMP_MNT_PARTITION}/sys
    umount ${TMP_MNT_PARTITION}/proc
    umount ${TMP_MNT_PARTITION}/dev
    umount ${TMP_MNT_PARTITION};
  fi # Partition was mounted ok

  return ${EXIT_VALUE}

} # function rtux_Chpasswd ()

# TODO: Program check runtime (Maybe to be stolen from bootinfoscript)

# MAIN PROGRAM

PASSWD_CHANGED_OK_STR="Password was changed OK! :). We recommend to change it once you're back in your system to use your system default encryption."
PASSWD_NOT_CHANGED_STR="Password was not changed. Something went wrong! :("
PASSWD_RUNNING_STR="Changing GNU/Linux password."
WHICH_USER_PASS_STR="Which user do you want to change its password?"

SELECTED_PARTITION=$(rtux_Choose_Linux_partition);

TMP_MNT_PARTITION=${RESCATUX_ROOT_MNT}/${SELECTED_PARTITION}
TMP_DEV_PARTITION=/dev/${SELECTED_PARTITION}
mkdir --parents ${TMP_MNT_PARTITION}
mount -t auto ${TMP_DEV_PARTITION} ${TMP_MNT_PARTITION} 2> /dev/null
  SYSTEM_USERS=$(rtux_User_List "${TMP_MNT_PARTITION}/etc/passwd")
umount ${TMP_MNT_PARTITION};

SELECTED_USER=$(rtux_Choose_User ${SYSTEM_USERS});
CHOOSEN_PASS=$(rtux_Enter_Pass ${SELECTED_USER})

if rtux_Run_Show_Progress "${PASSWD_RUNNING_STR}" rtux_Chpasswd ${SELECTED_PARTITION} ${SELECTED_USER} ${CHOOSEN_PASS}; then
  rtux_Message_Success ${PASSWD_CHANGED_OK_STR}
else
  rtux_Message_Failure ${PASSWD_NOT_CHANGED_STR}
fi


