#!/bin/bash
source ${RESCATUX_LIB_FILE}

# Top right corner
WIDTH=600
HEIGHT=460
GRAVITY=0
DESKTOP_WIDTH=`rtux_Get_Desktop_Width()`
let X_POSITION=${DESKTOP_WIDTH}-${WIDTH}
Y_POSITION=0

USER_NUMBER=$$
let USER_NUMBER_2=$USER_NUMBER+1
let USER_NUMBER_3=$USER_NUMBER+2

mkdir --parents $HOME/.xchat2/

cat << EOF > $HOME/.xchat2/xchat.conf
irc_nick1 = ${RESC_USER_IRC_PREFIX}${USER_NUMBER}
irc_nick2 = ${RESC_USER_IRC_PREFIX}${USER_NUMBER_2}
irc_nick3 = ${RESC_USER_IRC_PREFIX}${USER_NUMBER_3}
EOF

${XCHAT_COMMAND} --url=${RESCATUX_IRC_URL} & 
sleep 2s;

wmctrl \
  -r ${XCHAT_WINDOW_STR} \
  -e ${GRAVITY},\
${X_POSITION},\
${Y_POSITION},\
${WIDTH},\
${HEIGHT}

