#!/bin/bash
# Rescapp Winmbr run script
# Copyright (C) 2012,2013,2014,2015,2016 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCATUX_LIB_FILE}

set -x
set -v

# Create Hybrid MBR in a GPT partition
# From the choosen hard disk

function rtux_Hybridmbr_Create () {

  local EXIT_VALUE=1 # Error by default
  local SELECTED_HARD_DISK="$1"

  sgdisk -h 1,2,3 /dev/${SELECTED_HARD_DISK}

  EXIT_VALUE=$?
  return ${EXIT_VALUE}

} # function rtux_Grub_Install ()



# MAIN PROGRAM


GPT_HYBRID_CREATED_OK_STR="Hybrid MBR was created OK! :)"
GPT_HYBRID_NOT_CREATED_STR="Hybrid MBR was not created. Something went wrong! :("
WHICH_HARD_DISK_CREATE_HYBRIDMBR_STR="Which hard disk to create hybrid MBR on?"

SELECTED_HARD_DISK=$(rtux_Choose_Hard_Disk "${WHICH_HARD_DISK_CREATE_HYBRIDMBR_STR}");

if rtux_Hybridmbr_Create ${SELECTED_HARD_DISK} ; then
  rtux_Message_Success ${GPT_HYBRID_CREATED_OK_STR}
else
  rtux_Message_Failure ${GPT_HYBRID_NOT_CREATED_STR}
fi


