#!/bin/bash
# Rescapp Chpasswd run script
# Copyright Adrian Gibanel Lopez
# Licensed under the GNU PUBLIC LICENSE 3.0

source ${RESCATUX_LIB_FILE}

set -x
set -v

# Change selected user's password from the choosen Linux partition
# 1 parametre = Selected partition
# 2 parametre = Selected user
# 3 parametre = Choosen password
function rtux_Chpasswd () {

  local EXIT_VALUE=1 # Error by default
  local SELECTED_PARTITION="$1"
  local SELECTED_USER="$2"
  local CHOOSEN_PASS="$3"

  local n_partition=${SELECTED_PARTITION}

  local TMP_MNT_PARTITION=${RESCATUX_ROOT_MNT}/${n_partition}
  local TMP_DEV_PARTITION=/dev/${n_partition}
  mkdir --parents ${TMP_MNT_PARTITION}
  if $(mount -t auto ${TMP_DEV_PARTITION} ${TMP_MNT_PARTITION} 2> /dev/null)
    then
    mount -o bind /dev ${TMP_MNT_PARTITION}/dev
    mount -o bind /proc ${TMP_MNT_PARTITION}/proc
    mount -o bind /sys ${TMP_MNT_PARTITION}/sys

    if [[ -e ${TMP_MNT_PARTITION}${LINUX_OS_DETECTOR} ]] ; then

      echo "${SELECTED_USER}:${CHOOSEN_PASS}" | chpasswd --root ${TMP_MNT_PARTITION}
		  
    fi # Linux detector was found
    umount ${TMP_MNT_PARTITION}/sys
    umount ${TMP_MNT_PARTITION}/proc
    umount ${TMP_MNT_PARTITION}/dev
    umount ${TMP_MNT_PARTITION};
  fi # Partition was mounted ok

  return ${EXIT_VALUE}

} # function rtux_Chpasswd ()

# TODO: Program check runtime (Maybe to be stolen from bootinfoscript)

# MAIN PROGRAM

PASSWD_CHANGED_OK_STR="Password was changed OK! :)"
PASSWD_NOT_CHANGED_STR="Password was not changed. Something went wrong! :("
WHICH_USER_PASS_STR="Which user do you want to change its password?"

SELECTED_PARTITION=$(rtux_Choose_Linux_partition);

local SYSTEM_USERS=$(rtux_User_List ${SELECTED_PARTITION})

SELECTED_USER=$(rtux_Choose_User ${SYSTEM_USERS});
CHOOSEN_PASS=$(rtux_Enter_Pass ${SELECTED_USER})

if rtux_Chpasswd ${SELECTED_PARTITION} ${SELECTED_USER} ${CHOOSEN_PASS}; then
  rtux_Message_Success ${PASSWD_CHANGED_OK_STR}
else
  rtux_Message_Failure ${PASSWD_NOT_CHANGED_STR}
fi


