#!/bin/bash
# Rescapp Boot Info Script run script
# Copyright (C) 2012,2013,2014,2015,2016 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCATUX_LIB_FILE}

set +x
set +v
# Exceptionally we remove verbose

# Run Boot Info script
function rtux_Boot_Info_Script () {
  
  if  $(dirname ${0})/${BOOT_INFO_SCRIPT_BINARY} --stdout; then    
    return 0; # Ok
  else
    return 1; # Error
  fi

} # rtux_Boot_Info_Script ()

# TODO: Program check runtime (Maybe to be stolen from bootinfoscript)

# MAIN PROGRAM


BOOT_INFO_SCRIPT_BINARY="bootinfoscript"

BOOT_INFO_SCRIPT_OK_STR="Boot Info Script was run OK! :)"
BOOT_INFO_SCRIPT_KO_STR="Boot Info Script had a problem. Something went wrong! :("

BOOT_INFO_SCRIPT_EXPLANATION="Check the Support menu in order to see how you can show, share, share on forums, etc. the Boot Info Script log."


if rtux_Boot_Info_Script ; then
  rtux_Message_Success ${BOOT_INFO_SCRIPT_OK_STR}
  rtux_Message_Success ${BOOT_INFO_SCRIPT_EXPLANATION}
else
  rtux_Message_Failure ${BOOT_INFO_SCRIPT_KO_STR}
fi


