#!/bin/bash
# Rescapp winpass run script
# Copyright Adrian Gibanel Lopez
# Licensed under the GNU PUBLIC LICENSE 3.0

source ${RESCATUX_LIB_FILE}

set -x
set -v


# Return Windows SAM user that the user chooses
# Every parametre is treated as the question to be asked to the user.
function rtux_Choose_Sam_User () {
  local text_to_ask="$@"
  local n=0
  local SAM_LIST_VALUES=""
  local DETECTED_SAM_USERS=() # Array
  DETECTED_SAM_USERS=${SAM_USERS}; # TODO: Pass as a parametre
  for n_sam_user in ${DETECTED_SAM_USERS}; do
    if [[ ${n} -eq 0 ]] ; then
      local SAM_LIST_VALUES="TRUE ${n_sam_user}"
    else
      local SAM_LIST_VALUES="${SAM_LIST_VALUES} FALSE ${n_sam_user}"
    fi
    let n=n+1
  done

  echo $(zenity ${ZENITY_COMMON_OPTIONS}  \
	--list  \
	--text "${text_to_ask}" \
	--radiolist  \
	--column "${SELECT_STR}" \
	--column "${SAM_USER_STR}" \
	${SAM_LIST_VALUES}); 

} # function rtux_Choose_Hard_Disk ()


# Reset windows password
# 1 parametre = Selected partition
function rtux_winpass_reset () {

  local EXIT_VALUE=1 # Error by default
  local SELECTED_PARTITION="$1"


  # Mount the partition
  local n_partition=${SELECTED_PARTITION}
  local TMP_MNT_PARTITION=${RESCATUX_ROOT_MNT}/${n_partition}
  local TMP_DEV_PARTITION=/dev/${n_partition}
  mkdir --parents ${TMP_MNT_PARTITION}
  if $(mount -t auto ${TMP_DEV_PARTITION} ${TMP_MNT_PARTITION} 2> /dev/null)
    then
  # Find the exact name for sam file
      for n_windir in ${TMP_MNT_PARTITION}/* ; do
	if [[ -e ${n_windir}\
"/[Ss][Yy][Ss][Tt][Ee][Mm]32\
/[Cc][Oo][Nn][Ff][Ii][Gg]\
/[Ss][Aa][Mm]"\
	]] ; then
	  SAM_FILE="${TMP_MNT_PARTITION}/${n_windir}\
/[Ss][Yy][Ss][Tt][Ee][Mm]32\
/[Cc][Oo][Nn][Ff][Ii][Gg]\
/[Ss][Aa][Mm]"
	fi

  # Find the exact name for security file
	if [[ -e ${n_windir}\
"/[Ss][Yy][Ss][Tt][Ee][Mm]32\
/[Cc][Oo][Nn][Ff][Ii][Gg]\
/[Ss][Ee][Cc][Uu][Rr][Ii][Tt][Yy]"\
	]] ; then
	  SECURITY_FILE="${TMP_MNT_PARTITION}/${n_windir}\
/[Ss][Yy][Ss][Tt][Ee][Mm]32\
/[Cc][Oo][Nn][Ff][Ii][Gg]\
/[Ss][Ee][Cc][Uu][Rr][Ii][Tt][Yy]"
	fi
      done
  # Backup of the files in a temporal folder
    # TODO
  # Define SAM_USERS as a bash array
      SAM_USERS=()
  # Obtain users from SAM file
      SAM_USERS=$( bkhive ${SYSTEM_FILE} /dev/stdout\
	| samdump2 ${SAM_FILE} /dev/stdin \
	| awk -F ":" '{print "\42"$1"\42"}' )

  # Ask the user which password to reset	
      CHOOSEN_USER=$(rtux_Choose_Sam_User \
      "Choose Windows user to reset its password")
  # Run chntpw -L sam-file security-file
	chntpw -u "${CHOOSEN_USER}" -L ${SAM_FILE} ${SECURITY_FILE};
  # Umount the partition

    umount ${TMP_MNT_PARTITION};
  fi # Partition was mounted ok

  return ${EXIT_VALUE}

} # function rtux_Grub_Install ()

# TODO: Program check runtime (Maybe to be stolen from bootinfoscript)

# MAIN PROGRAM

# TODO: FETCH WIDTH AND HEIGHT FROM COMMAND LINE OR SO


SAM_USER_STR="Windows user"

WINPASS_RESET_OK_STR="Windows password was reset OK! :)"
WINPASS_NOT_RESET_STR="Windows password was not reset. Something went wrong! :("


SELECTED_PARTITION=$(rtux_Get_Windows_Os_Partitions);



if rtux_winpass_reset ${SELECTED_PARTITION} ; then
  rtux_Message_Success ${WINPASS_RESET_OK_STR}
else
  rtux_Message_Failure ${WINPASS_NOT_RESET_STR}
fi


