#!/bin/bash
# Rescapp Update-grub run script
# Copyright (C) 2012,2013,2014,2015,2016 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCATUX_LIB_FILE}
set -x
set -v

# MAIN PROGRAM

UEFICREATE_OK_STR="New UEFI Boot entry was added OK! :)"
UEFICREATE_KO_STR="New UEFI Boot entry addition went wrong! :("
UEFICREATE_RUNNING_STR="Adding new UEFI Boot entry."

SELECTED_EFI_PARTITION="$(rtux_Choose_EFI_System_partition)"
if rtux_Run_Show_Progress "${UEFICREATE_RUNNING_STR}" rtux_UEFI_Add_Boot_Entry "${SELECTED_EFI_PARTITION}" "$(rtux_UEFI_Choose_EFI_File ${SELECTED_EFI_PARTITION})";
then
  rtux_Message_Success ${UEFICREATE_OK_STR}
else
  rtux_Message_Failure ${UEFICREATE_KO_STR}
fi


#
