#!/bin/bash
# Rescapp Fsck run script
# Copyright (C) 2012,2013,2014,2015,2016 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCATUX_LIB_FILE}

set -x
set -v


# fsck Main program

FSCK_FORCED_OK_STR="Filesystem check with automatic fix was OK! :)"
FSCK_FORCED_KO_STR="Filesystem check with automatic fix went wrong! :("

SELECTED_PARTITION=$(rtux_Choose_Partition)

if ( rtux_Fsck_Forced ${SELECTED_PARTITION} ) ; then
  rtux_Message_Success ${FSCK_FORCED_OK_STR}
else 
  rtux_Message_Failure ${FSCK_FORCED_KO_STR}
fi
