#!/bin/bash
source ${RESCATUX_LIB_FILE}

LOG_CHOOSE_STR="Please choose a log file"
LOG_STR="log"
PASTEBIN_HINT="Right-click and select copy please. You will be able to paste it later at the chat option"

for ffile in ${RESCATUX_PATH}${LOG_DIRECTORY}/* ; do
  m=1
  BFILE=basename $ffile
  if [[ m -eq 1 ]] ; then
    LOG_LIST_VALUES="TRUE ${BFILE}"
  else
    LOG_LIST_VALUES="FALSE ${BFILE}"
  fi
done

SELECTED_FILE=$(zenity ${ZENITY_COMMON_OPTIONS} \
	  --list  \
	  --text "${LOG_CHOOSE_STR}" \
	  --radiolist  \
	  --column "${SELECT_STR}" \
	  --column "${LOG_STR}" \
	  ${LOG_LIST_VALUES});

PASTEBIN_URL=$(cat ${RESCATUX_PATH}${LOG_DIRECTORY}\
/${SELECTED_FILE} |\
pastebinit -b ${RESCATUX_PASTEBIN_URL} \
-a resc_$$ -f bash)

zenity ${ZENITY_COMMON_OPTIONS} \
	--entry \
	--text "${PASTEBIN_HINT}" \
	--entry-text="${PASTEBIN_URL}"

