#!/bin/bash
# Rescapp Winmbr run script
# Copyright (C) 2012 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCATUX_LIB_FILE}

set -x
set -v

# Compute Hybrid MBR CHS in a GPT partition
# From the choosen hard disk

function rtux_Hybridmbr_CHS_Compute () {

  local EXIT_VALUE=1 # Error by default
  local SELECTED_HARD_DISK="$1"

  sgdisk -C /dev/${SELECTED_HARD_DISK}

  EXIT_VALUE=$?
  return ${EXIT_VALUE}

} # function rtux_Grub_Install ()



# MAIN PROGRAM


GPT_HYBRID_CHS_COMPUTED_OK_STR="Hybrid MBR CHS was recomputed OK! :)"
GPT_HYBRID_CHS_NOT_COMPUTED_STR="Hybrid MBR was not recomputed. Something went wrong! :("
WHICH_HARD_DISK_CHS_COMPUTE_HYBRIDMBR_STR="Which hard disk to recompute its hybrid MBR CHS on?"

SELECTED_HARD_DISK=$(rtux_Choose_Hard_Disk "${WHICH_HARD_DISK_CHS_COMPUTE_HYBRIDMBR_STR}");

if rtux_Hybridmbr_CHS_Compute ${SELECTED_HARD_DISK} ; then
  rtux_Message_Success ${GPT_HYBRID_CHS_COMPUTED_OK_STR}
else
  rtux_Message_Failure ${GPT_HYBRID_CHS_NOT_COMPUTED_STR}
fi


