#!/bin/bash
# Rescapp Update-grub run script
# Copyright (C) 2012,2013,2014,2015,2016 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCATUX_LIB_FILE}
set -x
set -v



# TODO: Program check runtime (Maybe to be stolen from bootinfoscript)




# MAIN PROGRAM


UPDATE_GRUB_OK_STR="Grub configuration was updated OK! :)"
UPDATE_GRUB_KO_STR="Grub configuration update went wrong! :("
UPDATE_GRUB_RUNNING_STR="Updating Grub configuration."

if rtux_Run_Show_Progress "${UPDATE_GRUB_RUNNING_STR}" rtux_Grub_Update_Config $(rtux_Choose_Linux_partition) $(rtux_Order_Hard_Disks) ; then
  rtux_Message_Success ${UPDATE_GRUB_OK_STR}
else
  rtux_Message_Failure ${UPDATE_GRUB_KO_STR}
fi


#
