#!/bin/bash
# Rescapp Winpass run script
# Copyright (C) 2012 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCATUX_LIB_FILE}

set -x
set -v






# TODO: Program check runtime (Maybe to be stolen from bootinfoscript)

# MAIN PROGRAM

# TODO: FETCH WIDTH AND HEIGHT FROM COMMAND LINE OR SO


SAM_USER_STR="Windows user"

WINPASS_RESET_OK_STR="Windows password was reset OK! :)"
WINPASS_NOT_RESET_STR="Windows password was not reset. Something went wrong! :("


SELECTED_PARTITION=$(rtux_Choose_Windows_partition);



if rtux_winpass_reset ${SELECTED_PARTITION} ; then
  rtux_Message_Success ${WINPASS_RESET_OK_STR}
else
  rtux_Message_Failure ${WINPASS_NOT_RESET_STR}
fi

