#!/bin/bash
# Rescapp Fsck run script
# Copyright (C) 2012,2013,2014,2015,2016 Adrian Gibanel Lopez
#
# Rescapp is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Rescapp is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Rescapp.  If not, see <http://www.gnu.org/licenses/>.

source ${RESCATUX_LIB_FILE}

set -x
set -v


# fsck Main program

UEFIPARTCHECK_OK_STR="EFI partition status was OK (Every test passed successfully.) ! :)"
UEFIPARTCHECK_KO_STR="This might not be a valid EFI partition. At least one test failed. :("
UEFIPARTCHECK_RUNNING_STR="Performing EFI partition status checks"

UEFIPARTCHECK_EFI_SYSTEM_DETECTED_OK_STR="EFI partition has been detected as EFI partition by fdisk :)"
UEFIPARTCHECK_EFI_SYSTEM_DETECTED_KO_STR="EFI partition has NOT been detected as EFI partition by fdisk. :("
UEFIPARTCHECK_EFI_SYSTEM_DETECTED_RUNNING_STR="Performing EFI partition detection by fdisk"

UEFIPARTCHECK_ESP_FLAG_OK_STR="EFI partition has an esp flag :)"
UEFIPARTCHECK_ESP_FLAG_KO_STR="EFI partition does not have an esp flag. :("
UEFIPARTCHECK_ESP_FLAG_RUNNING_STR="Performing EFI partition esp flag check"

UEFIPARTCHECK_BOOT_FLAG_OK_STR="EFI partition has a boot flag :)"
UEFIPARTCHECK_BOOT_FLAG_KO_STR="EFI partition does not have a boot flag. :("
UEFIPARTCHECK_BOOT_FLAG_RUNNING_STR="Performing EFI partition boot flag check"

UEFIPARTCHECK_UEFI_FILESYSTEM_OK_STR="EFI partition has a valid uefi filesystem :)"
UEFIPARTCHECK_UEFI_FILESYSTEM_KO_STR="EFI partition does not have a valid uefi filesystem. :("
UEFIPARTCHECK_UEFI_FILESYSTEM_RUNNING_STR="Performing EFI partition valid uefi filesystem check"

UEFIPARTCHECK_PARTITION_MOUNT_OK_STR="EFI partition can be mount :)"
UEFIPARTCHECK_PARTITION_MOUNT_KO_STR="EFI partition cannot be mount. :("
UEFIPARTCHECK_PARTITION_MOUNT_RUNNING_STR="Performing EFI partition mount check"

SELECTED_PARTITION=$(rtux_Choose_Partition)






EXIT_SUM=0


if ( rtux_Run_Show_Progress "${UEFIPARTCHECK_EFI_SYSTEM_DETECTED_RUNNING_STR}" rtux_UEFI_Check_Is_EFI_System_Partition ${SELECTED_PARTITION} ) ; then
  rtux_Message_Success ${UEFIPARTCHECK_EFI_SYSTEM_DETECTED_OK_STR}
else
  rtux_Message_Failure ${UEFIPARTCHECK_EFI_SYSTEM_DETECTED_KO_STR}
  false
fi

UEFIPARTCHECK_EFI_SYSTEM_DETECTED_EXIT_VALUE=$?
EXIT_SUM=$((EXIT_SUM+UEFIPARTCHECK_EFI_SYSTEM_DETECTED_EXIT_VALUE))


if ( rtux_Run_Show_Progress "${UEFIPARTCHECK_ESP_FLAG_RUNNING_STR}" rtux_UEFI_Part_Check_esp_Flag ${SELECTED_PARTITION} ) ; then
  rtux_Message_Success ${UEFIPARTCHECK_ESP_FLAG_OK_STR}
else
  rtux_Message_Failure ${UEFIPARTCHECK_ESP_FLAG_KO_STR}
  false
fi

UEFIPARTCHECK_ESP_FLAG_EXIT_VALUE=$?
EXIT_SUM=$((EXIT_SUM+UEFIPARTCHECK_ESP_FLAG_EXIT_VALUE))


if ( rtux_Run_Show_Progress "${UEFIPARTCHECK_BOOT_FLAG_RUNNING_STR}" rtux_UEFI_Part_Check_boot_Flag ${SELECTED_PARTITION} ) ; then
  rtux_Message_Success ${UEFIPARTCHECK_BOOT_FLAG_OK_STR}
else
  rtux_Message_Failure ${UEFIPARTCHECK_BOOT_FLAG_KO_STR}
  false
fi

UEFIPARTCHECK_BOOT_FLAG_EXIT_VALUE=$?
EXIT_SUM=$((EXIT_SUM+UEFIPARTCHECK_BOOT_FLAG_EXIT_VALUE))


if ( rtux_Run_Show_Progress "${UEFIPARTCHECK_UEFI_FILESYSTEM_RUNNING_STR}" rtux_UEFI_Part_Check_uefi_filesystem ${SELECTED_PARTITION} ) ; then
  rtux_Message_Success ${UEFIPARTCHECK_UEFI_FILESYSTEM_OK_STR}
else
  rtux_Message_Failure ${UEFIPARTCHECK_UEFI_FILESYSTEM_KO_STR}
  false
fi

UEFIPARTCHECK_UEFI_FILESYSTEM_EXIT_VALUE=$?
EXIT_SUM=$((EXIT_SUM+UEFIPARTCHECK_UEFI_FILESYSTEM_EXIT_VALUE))


if ( rtux_Run_Show_Progress "${UEFIPARTCHECK_PARTITION_MOUNT_RUNNING_STR}" rtux_Partition_Can_Be_Mount ${SELECTED_PARTITION} ) ; then
  rtux_Message_Success ${UEFIPARTCHECK_PARTITION_MOUNT_OK_STR}
else
  rtux_Message_Failure ${UEFIPARTCHECK_PARTITION_MOUNT_KO_STR}
  false
fi

UEFIPARTCHECK_PARTITION_MOUNT_EXIT_VALUE=$?
EXIT_SUM=$((EXIT_SUM+UEFIPARTCHECK_PARTITION_MOUNT_EXIT_VALUE))


if [ ${EXIT_SUM} -eq 0 ] ; then
  rtux_Message_Success ${UEFIPARTCHECK_OK_STR}
else 
  rtux_Message_Failure ${UEFIPARTCHECK_KO_STR}
fi
