#!/bin/bash
source ${RESCATUX_LIB_FILE}

# Top left corner
WIDTH=600
HEIGHT=460
GRAVITY=0

X_POSITION=0
Y_POSITION=0

${FIREFOX_COMMAND} --new-window http://rescatux.berlios.de &
sleep 5s;

wmctrl \
  -r ${FIREFOX_WINDOW_STR} \
  -e ${GRAVITY},\
${X_POSITION},\
${Y_POSITION},\
${WIDTH},\
${HEIGHT}
